files:
  - source: /filepicker/src/main/res/values/strings.xml
    translation: /filepicker/src/main/res/values-%two_letters_code%/%original_file_name%
    type: android
    dest: /filepicker/strings.xml